### ISSUE TITLE
wrong aspect ratio

### ISSUE THREAD

**Issue by HYMXDEV** [Cpt-T-Krik/rbtv_mission_control#1]
I noticed that the YouTube logo in the sidebar as well as in the channel selection (the classname is "ytNav") have got the wrong aspect ratio, because of the static image sizes. Is this your intention to get equally sized icons or just a mistake?
![rbtv_mc_wrong_aspect_ratio](https://cloud.githubusercontent.com/assets/12176022/7400425/28378e84-eebd-11e4-83ca-7c9e584f01bc.jpg)

**Comment by Cpt-T-Krik** [comment]
It was my intention to get equally sized icons for the navigation but not to get a wrong aspect ration for the YouTube logo. Since I'm not that deep into CSS I just wanted a UL element for a vertical navigation with equally sized li Elements. Therefore I had to bring the icons to the same aspect ratio. I didn't noticed that with the current approach the YouTube logo has ja wrong aspect ratio. Feel free to fix this issue.

**Comment by Cpt-T-Krik** [comment]
After all I think this is not really a issue that needs to be fixed. I suggest to close this issue.
